### ISSUE TITLE
Close does not unblock pending Read call

### ISSUE THREAD

**Issue by dsnet** [songgao/water#22]
I am running `go1.8` on `Linux carbonite 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`.

Consider the following test:
```go
func main() {
	iface, _ := water.NewTUN("tunnel")
	exec.Command("/sbin/ip", "addr", "add", "10.0.0.1/24", "dev", "tunnel").Run()
	exec.Command("/sbin/ip", "link", "set", "dev", "tunnel", "up").Run()

	c := make(chan bool)
	go func() {
		iface.Read(make([]byte, 1<<16))
		fmt.Println("Read returned")
		c <- true
	}()

	time.Sleep(5 * time.Second)

	fmt.Println("calling Close")
	iface.Close() // This should unblock Read
	<-c           // Wait for Read to unblock
}
```

Running this program hangs forever with the following output:
```
$ go build main.go
$ sudo ./main
calling Close
```
But never prints "Read returned" because the Read call is never interrupted even though the iface has been closed.

While it is blocked, `ifconfig` still shows the device is up:
```
$ ifconfig
tunnel    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.0.0.1  P-t-P:10.0.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Interestingly, if you `ping -b 10.0.0.255`, then the Read operation returns with a valid packet, but if you were to try calling Read again, it properly reports that the device is closed.

The fact that Close does not interrupt pending Read calls is unexpected behavior since it is contrary to how other networking handlers like sockets operate.

**Comment by Gnouc** [comment]
@dsnet If we set the interface underlying file descriptor to non-blocking mode:

```
if err := syscall.SetNonblock(int(fd), true); err != nil {                                                                                                                                                                            
                return err                              (https://github.com/songgao/water/blob/80efdb69919407412ee56a5e3abb0a4b6499657a/ipv4_test.go#L26) failed. Change the code to:

```
if err := syscall.SetNonblock(int(fd), false); err != nil {                                                                                                                                                                            
                return err                                                                                                                                                                                                                    
        }
```

works for both.

**Comment by moshuipan** [comment]
it will be  blocked when open a net device to read or write, maybe u can set deadline to before operate file descripitor :smile:.
