### ISSUE TITLE
Doesn't work as the example indicates

### ISSUE THREAD

**Issue by ajeecai** [songgao/water#28]
Hi,

I tried with the example "TAP on Linux" in README page, on Ubuntu 16.04, go 1.8.1, strictly following the instructions. After issuing "sudo ip link set dev O_O up", using ifconfig will show 

```
O_O       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.1.0.10  P-t-P:10.1.0.10  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:84 (84.0 B)
```

For me I had though Link encap should be Ethernet? 

"ping -c1 -b 10.1.0.255",  the output of the main.go terminal is: 
```
2017/08/27 19:43:08 Dst: 45:00:00:54:00:00
2017/08/27 19:43:08 Src: 40:00:40:01:25:9f
2017/08/27 19:43:08 Ethertype: 0a 01 <---- (  not as the example said Ethertype: 08 00)
2017/08/27 19:43:08 Payload: 00 0a 0a 01 00 ff 08 00 0f 24 7c c1 00 01 4c b0 a2 59 00 00 00 00 b0 3c 0e 00 00 00 00 00 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32 33 34 35 36 37
```
And I tried to "ping 10.1.0.10", there are ICMP replies but no output from main.go terminal, means the frames not read from TAP? 

Is there anything I am doing wrong or misunderstanding?  I didn't take a look through the code but want to ask first for shortcut.

Thanks

**Comment by songgao** [comment]
Resolved by https://github.com/songgao/water/pull/30
