### ISSUE TITLE
How to implement tun/tap in OSX?

### ISSUE THREAD

**Issue by chzyer** [songgao/water#3]
Hi~
I have seen the roadmap about `water` that will support for OSX, did you already have any idea to support it? 
I found a project [tuntaposx](http://tuntaposx.sourceforge.net/download.xhtml), but I think that would be another way that cat support tuntap on OSX without install any software, just like `Tunnelblick`.

**Comment by hsheth2** [comment]
@chzyer I had originally tried to implement OSX support using `utun`, but it was difficult due to the limited documentation. `Tunnelblick` is simply a user interface for `OpenVPN`, which uses this same `utun` device. Currently, I am trying to add support on OSX using `tuntaposx`, although I am open to any ideas on how to avoid this dependency.

**Comment by chzyer** [comment]
@hsheth2 
I found that `Tunnelblick` is bring the `tap`/ `tun` kernel extensions, so if we run commands follows:
```
sudo kextload /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext
sudo kextload /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext
```
Some files like `tunX` and `tapX` will appeared in the `/dev`, but it still have two problems:
1. I'm not sure that we can just copy these two `.kext` files into another which is not installed `Tunnelblick` yet.
2. How to create a interface that point to the `fd` which get by opening `/dev/tunX`?

**Comment by chzyer** [comment]
I just wrote some c code follow [openvpn](https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/tun.c#L2712-L2819) and simplify it to follows.
It will create a `utun9` interface, I hope this will works. Tested in OSX 10.11

```{c}
#include <stdio.h>
#include <sys/socket.h>
#include <sys/sys_domain.h>
#include <unistd.h>

#include <string.h> // strlcpy

#include <sys/ioctl.h> // ioctl
#include <sys/kern_control.h> // struct socketaddr_ctl
#include <net/if_utun.h> // UTUN_CONTROL_NAME

#include <fcntl.h>


int utun_open() {
	struct ctl_info ctlInfo;
	strlcpy(ctlInfo.ctl_name, UTUN_CONTROL_NAME, sizeof(ctlInfo.ctl_name));
		 
	int fd;
	fd = socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL);
	if (fd < 0) {
		perror("socket");
		return fd;
	}
	
	struct sockaddr_ctl sc;

	if (ioctl(fd, CTLIOCGINFO, &ctlInfo) == -1) {
		close(fd);
		perror("ioctl");
		return -1;
	}
	printf("ctl_info: {ctl_id: %ud, ctl_name: %s}",
		   ctlInfo.ctl_id, ctlInfo.ctl_name);

	sc.sc_id = ctlInfo.ctl_id;
	sc.sc_len = sizeof(sc);
	sc.sc_family = AF_SYSTEM;
	sc.ss_sysaddr = AF_SYS_CONTROL;
	sc.sc_unit = 10;

	if (connect(fd, (struct sockaddr *)&sc, sizeof(sc)) < 0) {
		perror("connect");
		close(fd);
		return -1;
    }

	// set_nonblock (fd);
	fcntl (fd, F_SETFL, O_NONBLOCK);
		
	// set_cloexec (fd);


	return fd;
}

int main() {
	int fd = utun_open();
	close(fd);
	printf("%d", fd);
	sleep(5);
	return 0;
}
```

**Comment by songgao** [comment]
Since `tuntaposx` seems to be the only feasible way to use `/dev/tun` on OS X for now, it seems to me that's a proper dependency for OS X, assuming installation is simple enough.

I haven't tried it myself yet. Is `brew install tuntap` sufficient on El Capitan?

**Comment by chzyer** [comment]
I don't think `tuntaposx` is the only feasible way, `OpenVPN` supports OS X as well.
Did you has been try my demo above? I'm already wrote a simple VPN based `utun` communicate with linux remote.
But I have no idea about `tap`, even OS X kernel whether support for it. `OpenVPN` maybe have the answer.

**Comment by songgao** [comment]
Thanks @chzyer! That does seem pretty promising. It should be straightforward to implement it through `syscall` or `golang.org/x/sys`. If `tap` doesn't work out-of-box, I think we can work out some solution that uses both, i.e., use `tuntaposx` if it is installed, otherwise fallback to `net/if_utun.h` and only support `tun`.

Would you have time to find out about `tap` through `net/if_utun.h`? If not, I'll take a look when I have time.

**Comment by songgao** [comment]
A quick search: [FreeBSD](https://github.com/freebsd/freebsd/tree/master/sys/net) has `if_tun.h` and `if_tap.h`, but [OS X](https://opensource.apple.com/source/xnu/xnu-1456.1.26/bsd/net/) only has `if_utun.h`. I'm not sure if `if_utun.h` is equivalent to just `if_tun.h` or both `if_tun.h` and `if_tap.h` though.
