### ISSUE TITLE
Failed to find the tap device in registry with specified ComponentId() on windows10

### ISSUE THREAD

**Issue by WANG-lp** [songgao/water#32]
Hi, I run your test code on windows 10 with go version 1.9,
it cannot find the tap device.

I already installed OpenVPN TAP driver and it works correctly on my PC.

The regkey of the TAP drive is the same as the string in your code and the default ComponentId is also same too.

**Comment by slot4im** [comment]
Same problem with example. It can be done with : 
```go
func main() {
	config := water.Config{
		DeviceType: water.TAP,
	}
	config.ComponentID = "tap0901"

	ifce, err := water.New(config)
	if err != nil {
		log.Fatal(err)
	}
	var frame ethernet.Frame
...
```

**Comment by songgao** [comment]
Sorry I don't have a Windows machine to test this at the time. @lixin9311 did all the fantastic Windows work like a ninja :)

@WANG-lp does @slot4im 's solution work for you?

**Comment by WANG-lp** [comment]
@slot4im @songgao It works. Thanks!
