### ISSUE TITLE
Can't write to tun

### ISSUE THREAD

**Issue by ly0** [songgao/water#33]
test code
```go
package main

import (
	"fmt"
	"github.com/songgao/water"
	"encoding/hex"
	"os"
	"time"
)

func main() {
	ifce, err := water.New(water.Config{
		DeviceType: water.TUN,
	})

	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "%v\n", ifce.Name())

	defer ifce.Close()

	for i := 1; i < 100; i++ {
		data, _ := hex.DecodeString("0200000045000054289d000040013ded0a01000a0a0100140800787f9f45000059db76250003253408090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637")
		ifce.Write(data)
		time.Sleep(1 * time.Second)

	}

}

```

Running on macos, and tunnel name is utun2, then I execute `sudo ifconfig utun2 10.1.0.10 10.1.0.20 up`  
data is an ICMP packet equivalent as `ping 10.1.0.20`
I captured at utun2 by wireshark, and get nothing, does my codes or my test get wrong?

**Comment by ly0** [comment]
Finally got success, only IP Layer's data is accepted. issue closed.

**Comment by songgao** [comment]
Yeah ICMP uses IP packets, so capturing on UDP or TCP won't give you anything. Glad you figured it out!

**Comment by ly0** [comment]
@songgao emmm...actually the real reason is here https://github.com/songgao/water/blob/master/syscalls_darwin.go#L178

**Comment by songgao** [comment]
Oh I thought you meant Wireshark didn’t capture IP layer.

Yeah that’s the required version field in the first byte of IP packets. See [this](https://en.m.wikipedia.org/wiki/IPv4#Header) for IPv4 and [this](https://en.m.wikipedia.org/wiki/IPv6_packet#Fixed_header) for IPv6.
