### ISSUE TITLE
flag.Parse() collects test files by mistake

### ISSUE THREAD

**Issue by tkojima** [songgao/water#4]
When I wrote a source code as follows:

```go
package main

import (
        "flag"
        "github.com/songgao/water"
)

func main() {
        flag.Parse()

        water.NewTUN("tun0")
}
```

and built and ran with `-h` option, a lot of unexpected options was listed:

```
vagrant@localhost:~/waterexample/src/main$ go build
vagrant@localhost:~/waterexample/src/main$ ls
main  main.go
vagrant@localhost:~/waterexample/src/main$ ./main -h
Usage of ./main:
  -test.bench string
        regular expression to select benchmarks to run
  -test.benchmem
        print memory allocations for benchmarks
  -test.benchtime duration
        approximate run time for each benchmark (default 1s)
  -test.blockprofile string
        write a goroutine blocking profile to the named file after execution
  -test.blockprofilerate int
        if >= 0, calls runtime.SetBlockProfileRate() (default 1)
  -test.count n
        run tests and benchmarks n times (default 1)
  -test.coverprofile string
        write a coverage profile to the named file after execution
  -test.cpu string
        comma-separated list of number of CPUs to use for each test
  -test.cpuprofile string
        write a cpu profile to the named file during execution
  -test.memprofile string
        write a memory profile to the named file after execution
  -test.memprofilerate int
        if >=0, sets runtime.MemProfileRate
  -test.outputdir string
        directory in which to write profiles
  -test.parallel int
        maximum test parallelism (default 2)
  -test.run string
        regular expression to select tests and examples to run
  -test.short
        run smaller test suite to save time
  -test.timeout duration
        if positive, sets an aggregate time limit for all tests
  -test.trace string
        write an execution trace to the named file after execution
  -test.v
        verbose: print additional output
```

It probably seems that `ipv4_test_linux.go` and `ipv4_test_other.go` caused the situation.
I tried to rename these tile names to:

- ipv4_test_linux.go -> ipv4_linux_test.go
- ipv4_test_other.go -> ipv4_other_test.go

and built and ran again, the problem was solved.

```
vagrant@localhost:~/waterexample/src/main$ go build
vagrant@localhost:~/waterexample/src/main$ ./main -h
Usage of ./main:
vagrant@localhost:~/waterexample/src/main$
```

Would you please consider to rename those file names?

**Comment by tkojima** [comment]
Additional information: Go version

```
$ go version
go version go1.5.2 linux/amd64
```

**Comment by songgao** [comment]
Interesting. Thanks for submitting the issue! I am traveling right now and not sure when I'll get a chance to try this. Does renaming the file break any testing mechanism on different platforms?

**Comment by tkojima** [comment]
On windows platform, the test code can't reach the function `setupIfce()` because `NewTAP` function returns an error.

https://github.com/songgao/water/blob/e7338c341f44c61494d5e024673677bcd3eaed17/ipv4_test.go#L39-L44

```
kojima@tkojima-note /c/golibs/src/github.com/songgao/water
$ go test
--- FAIL: TestBroadcast (0.00s)
        ipv4_test.go:41: creating TAP error: tap interface not implemented on this platform
FAIL
exit status 1
FAIL    github.com/songgao/water        0.057s
```

Parhaps, it is not necessary to provide `setupIfce` function for each platform?
(i.e. `setupIfce` is called only linux platform after all.)

**Comment by songgao** [comment]
I see. Thanks @tkojima ! We don't have code for Windows yet, so even with the flag parsing issue fixed, it still won't work. I'd love it if it can work on Windows as well though. Do you have any experience with TUN/TAP devices on Windows?

**Comment by tkojima** [comment]
> Do you have any experience with TUN/TAP devices on Windows?

Sorry, I haven't any experience with it.
I hope to fix the flag parsing issue on linux platform.

I think renaming the file doesn't break testing mechanism on different platforms.

**Comment by songgao** [comment]
No worries! I looked a bit more at the `go build` [docs](https://golang.org/pkg/go/build/) and it turns out that your proposed name changes are actually backed by documented feature:

> If a file's name, after stripping the extension and a possible _test suffix, matches any of the following patterns:

> ```
> *_GOOS
> *_GOARCH
> *_GOOS_GOARCH
> ```
> ...

Since `_test` is the first stripped out suffix, it's the right call to move it to the last. Would you mind making a pull request containing the renaming? (Since you found the issue I thought the commit author should be you :D)

Also, I just realize I didn't see your comment on `setupIfce` in previous comment. I think it's still necessary since the commands to run to set up IPs are different for Linux (`ip`), OS X (`ifconfig`), BSD (`ifconfig`), and Windows (`ipconfig`?). In the future we might switch to a library that handles all these stuff (it's only for testing after all), but for now it seems necessary.

**Comment by tkojima** [comment]
OK, I have made a pull request #5 to fix the issue.

**Comment by songgao** [comment]
Merged :D Thanks @tkojima !

**Comment by tkojima** [comment]
Thanks!
