### ISSUE TITLE
The windows example can't run

### ISSUE THREAD

**Issue by pencil001** [songgao/water#41]
I use openvpn install the tap driver on my windows
```bash
C:\Program Files\TAP-Windows\bin
λ  .\tapinstall.exe hwids tap0901
ROOT\NET\0000
    Name: TAP-Windows Adapter V9
    Hardware IDs:
        tap0901
1 matching device(s) found.
```

Then I copy the code and run the program
```bash
 go run .\main.go
```
It always show me the error
```bash
2018/03/30 19:09:41 Failed to find the tap device in registry with specified ComponentId(), TAP driver may be not installed
exit status 1
```

**Comment by lixin9311** [comment]
I think we should update the README file, change the config parameter in the example code, 

`water.Config{
		DeviceType: water.TAP,
		PlatformSpecificParams: water.defaultPlatformSpecificParams()
}`

**Comment by songgao** [comment]
Ah I see; looks like I had a bug here where it didn't automatically populate defaultPlatformSpecificParams(). Will fix. Thanks.

**Comment by songgao** [comment]
@pencil001 would you mind trying it again with latest master?

**Comment by pencil001** [comment]
@songgao Yes, it's worked.
