### ISSUE TITLE
Document threading properties of Ifce

### ISSUE THREAD

**Issue by calder** [songgao/water#44]
Starter questions:
* Can multiple goroutines concurrently `Read` from the same `Ifce`?
* Can multiple goroutines concurrently `Write` to the same `Ifce`?
* Are there performance bottlenecks that limit `Read` and `Write` calls by multiple threads?

**Comment by songgao** [comment]
Each interface corresponds to a file descriptor, so it probably doesn’t make sense to have multiple threads working on the same interface. If The goal is to have parallel streams to increase throughout, Linux has multiqueue support for TUN/TAP: https://www.kernel.org/doc/Documentation/networking/tuntap.txt

**Comment by songgao** [comment]
Closing. Feel free to reopen if you have further questions.
