### ISSUE TITLE
How to have concurrent TUN/TAP interfaces on Windows ?

### ISSUE THREAD

**Issue by gumyn** [songgao/water#46]
I tried to start on WINDOWS a new TUN interface while OpenVPN was running and "songgao/water" library couldn't find an interface and doesn't try to create a new one.

Is it possible to have parallel interfaces on windows ?

(Linux and Mac are working fine)

**Comment by songgao** [comment]
@lixin9311 knows better about the windows support, but it seems in this case OpenVPN has already occupied the interface, so you can't use it. I suppose that's what you mean by "parallel interfaces", i.e. you need a second TUN interface and set [ComponentID](https://github.com/songgao/water/blob/bf1a5d02778fcf40c282de352a53b1fe1f5b9f96/params_windows.go#L8). I don't remember clearly how to do that, perhaps @lixin9311 can clarify?

**Comment by lixin9311** [comment]
Please refer to this page,
https://community.openvpn.net/openvpn/wiki/ManagingWindowsTAPDrivers
maybe we should add it to README regarding how to set up a TUN/TAP device.

**Comment by songgao** [comment]
Looks like this was fixed by https://github.com/songgao/water/pull/59 . I'm gonna go ahead and close this for now but @gumyn feel free to reopen if you think other work needs to be done for this.
