### ISSUE TITLE
Bug: write /dev/net/tun: invalid argument on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by Gnouc** [songgao/water#47]
I'm using govpn to connect from Windows client to my Linux server:

 - Server code: https://github.com/bclermont/govpn/tree/develop-prev-peer-disconnect/src/cypherpunks.ru/govpn/server
 - Client code: https://github.com/bclermont/govpn/tree/develop-prev-peer-disconnect/src/cypherpunks.ru/govpn/client

The code to setup windows TAP is got from water example: https://github.com/bclermont/govpn/blob/develop-prev-peer-disconnect/src/cypherpunks.ru/govpn/tap_windows.go

From windows client, everything is fine, tap adapter is setup correctly, set IP address, ping itself ok, and there's traffic go out of it.

In VPN server, the ifconfig shown that there're packets are dropped, and server log said that:

```
{"data":67,"error":"t.dev.Write 42: write /dev/net/tun: invalid argument"}
```

I'm not sure it's the same issue with https://github.com/songgao/water/issues/18 or not.

**Comment by songgao** [comment]
Sorry for the lack of response in weeks!

I tried to look at your code, but with all the govpn code and encoding/decoding stuff, it's a bit hard for me to follow everything and tell where it went wrong. If you can post some independent code that only involves this package, that'd help. It may also be helpful to just post packet content that the Linux server code is trying to write into the tap interface if you don't want to put together an example.

**Comment by Gnouc** [comment]
@songgao so we found the issue, my windows client use TAP interface but my server create a TUN interface instead, that's why we got invalid write.

Thanks for support.
