### ISSUE TITLE
Read with timeout

### ISSUE THREAD

**Issue by weiyixuan** [songgao/water#54]
Is there any way to read ifce with timeout?

**Comment by songgao** [comment]
I haven't tried it myself yet, but it shouldn't be hard to add `SetReadDeadline` after https://github.com/songgao/water/pull/53 is in.

**Comment by weiyixuan** [comment]
I just want to do a timeout read, not shut down the device.

**Comment by songgao** [comment]
I understand. I was just saying to adding these IO deadline method is simple once that PR is in first. Sorry for not making it clear earlier.

I’ll get to it soon. Or if you like, feel free to put up a PR.

**Comment by weiyixuan** [comment]
I still haven't found an easy way to read and write over time. Finally, the go-winio library is adopted and part of the code is extracted for implementation.
