### ISSUE TITLE
Accessing existing TAP interface

### ISSUE THREAD

**Issue by gdm85** [songgao/water#6]
Is it possible to use an existing TAP interface? If not, am I correct to think that it's just a matter to add some code in order to achieve that?

**Comment by songgao** [comment]
Hi @gdm85 ! I'm not aware of a way to do that. If I understand correctly, you need an exclusive file descriptor to own a TUN/TAP interface, and when you close the file descriptor, the interface is destroyed.

I could be wrong though. Did you see this done somewhere?

**Comment by gdm85** [comment]
@songgao I actually was looking up this:
http://backreference.org/2010/03/26/tuntap-interface-tutorial/

And apparently it is possible! Criteria:

> As said, it turns out that the code to (re)attach to an existing tun/tap interface is the same as the code used to create it; in other words, tun_alloc() can again be used. When doing so, for it to be successful three things must happen:
> 
> * The interface must exist already and be owned by the same user that is attempting to connect (and probably be persistent)
> * the user must have read/write permissions on /dev/net/tun
> * The flags provided must match those used to create the interface (eg if it was created with IFF_TUN then the same flag must be used when reattaching)

So I think it would be possible to add the functionality here to `water` :)

**Comment by songgao** [comment]
@gdm85 Thanks for the link! It looks like nothing special needs to be done to reattach an existing interface, if the interface was created persistent. Have you tried calling `NewTAP` with name of an existing tap interface yet?

**Comment by gdm85** [comment]
@songgao that doesn't work, but I think that by creating it with assigned user and group it may work
