### ISSUE TITLE
Can't expose device fd on  windows

### ISSUE THREAD

**Issue by chengxuncc** [songgao/water#60]
I can't expose fd on windows like #7 before.
>When I use  type assertion, and get this:
`panic: interface conversion: io.ReadWriteCloser is *water.wfile, not *os.File`
Environment:
`windows10, golang 1.12, amd64`

**Comment by songgao** [comment]
@chengxuncc Thanks for the issue. Could you explain what you are using the FD for on Windows? Ideally operations that require direct access to the FD (or Handle on Windows) would be included in this package.

**Comment by chengxuncc** [comment]
I just run this code on windows:
``` go
package main

import (
    "log"
    "os"

    "github.com/songgao/water"
)

func main() {
    ifce, err := water.NewTUN("haha")
    if err != nil {
        log.Fatalf("creating TUN interface error: %v\n", err)
    }
    log.Printf("file fd: %d\n", ifce.ReadWriteCloser.(*os.File).Fd())
}
```

_Originally posted by @songgao in https://github.com/songgao/water/issues/7#issuecomment-210862889_

I use the FD to configure dhcp IP and dns, which can also be implemented by netsh or some ways else, but winodws can show notifications that IP was allocated on device in the FD way.

**Comment by songgao** [comment]
Interesting. I'll put up a PR to add a `Sys()` method for that. Thanks for bringing it up!
