### ISSUE TITLE
implement an interface to expose device fd

### ISSUE THREAD

**Issue by radaiming** [songgao/water#7]
Hi,

I want to run some extra syscalls to the device, but looks I could not get the device fd, could you please implement an interface to expose it? Thanks.

**Comment by songgao** [comment]
@radaiming Thanks for the request. I've made some changes to the `Interface` type and now it should be possible to get `*os.File` through type assertion. For example:

```go
package main

import (
	"log"
	"os"

	"github.com/songgao/water"
)

func main() {
	ifce, err := water.NewTUN("haha")
	if err != nil {
		log.Fatalf("creating TUN interface error: %v\n", err)
	}
	log.Printf("file fd: %d\n", ifce.ReadWriteCloser.(*os.File).Fd())
}
```

**Comment by radaiming** [comment]
Really thanks for your quick work :+1:

**Comment by chengxuncc** [comment]
When I use  type assertion, and get this:
`panic: interface conversion: io.ReadWriteCloser is *water.wfile, not *os.File`

Environment:
`windows10, golang 1.12, amd64`
