### ISSUE TITLE
write tun: invalid argument on Debian

### ISSUE THREAD

**Issue by CrazyHulk** [songgao/water#71]
I an using vpn to connect from iPhone client to my Linux server:

I create a tcp connect between clien and server,  read packets from iphone and write to tun interface. But I  get an error after write some packets: "write tun: invalid argument".

`
for {

        bufPool.Resize(1500)
        count, aErr := io.ReadFull(conn, bufPool)
        if aErr != nil {
                log.Printf("read failed %s\n", err)
                return
        }
        validBuf := bufPool[:count]
 
        n, aErr := gl_ifce.Write(validBuf)
        if aErr != nil {
                fmt.Println(n, count, aErr)
                return
        } 
}
`

**Comment by archit120** [comment]
@CrazyHulk Did you figure this out?

**Comment by crazyhulk** [comment]
Yes, it works well.
