### ISSUE TITLE
IP packet or Ethernet frame?

### ISSUE THREAD

**Issue by caleb-letsgo** [songgao/water#75]
On the Windows platform, can I just work with IP packets and not care about frame headers? Thanks.

**Comment by songgao** [comment]
TUN mode gives you IP packets and TAP mode gives you ethernet frames. It seems TUN is what you want.

**Comment by caleb-letsgo** [comment]
Is tun supported on the Windows platform?

**Comment by lixin9311** [comment]
As long as you config it correctly.

FYI:

https://github.com/slackhq/nebula/blob/master/tun_windows.go

**Comment by caleb-letsgo** [comment]
thanks
